const AuthActionTypes = {
    USER_UPSERT_REQUEST: 'USER_UPSERT_REQUEST',
    USER_UPSERT_SUCCESS: 'USER_UPSERT_SUCCESS',
    USER_UPSERT_FAILURE: 'USER_UPSERT_FAILURE',
    STORE_TOKEN: 'STORE_TOKEN',
    LOGOUT: 'LOGOUT'
};

export default AuthActionTypes;