const BooksActionTypes = {
    BOOKS_REQUEST: 'BOOKS_REQUEST',
    BOOKS_READING_SUCCESS: 'BOOKS_READING_SUCCESS',
    BOOKS_READING_FAILURE: 'BOOKS_READING_FAILURE',
    BOOKS_ADDED_SUCCESS: 'BOOKS_ADDED_SUCCESS',
    BOOKS_ADDED_FAILURE: 'BOOKS_ADDED_FAILURE',
    BOOKS_FINISHED_SUCCESS: 'BOOKS_FINISHED_SUCCESS',
    BOOKS_FINISHED_FAILURE: 'BOOKS_FINISHED_FAILURE',
};

export default BooksActionTypes;